package kg.geektech.game.players;

public enum SuperAbility {
    CRITICAL_DAMAGE, HEAL, BOOST, SAVE_DAMAGE_AND_REVERT, TAKES_SOME_OF_THE_DAMAGE, REVIVES_THE_FIRST_DECEASED,
    SUMMONED_ANGEL_OR_RAVEN, STUN, FREEZE
}
